4 PRINT "TIME - SPEED - DISTANCE EXERCISE"
5 PRINT
10 RANDOMIZE
15 C = INT(RND * 25) + 40
20 D = INT(RND * 15) + 5
25 T = INT(RND * 19) + 20
30 PRINT "A CAR TRAVELING " + STR$(C) + " MPH CAN MAKE A CERTAIN TRIP IN"
35 PRINT STR$(D) + " HOURS LESS THAN A TRAIN TRAVELING AT " + STR$(T) + " MPH."
40 PRINT "HOW LONG DOES THE TRIP TAKE BY CAR";
45 INPUT A
50 V = D * T / (C - T)
55 E = INT(ABS(V - A) * 100 / A + 0.5)
60 IF E <= 5 THEN GOTO 90
65 PRINT "GOOD! ANSWER WITHIN " + STR$(E) + " PERCENT."
70 GOTO 100
80 PRINT "SORRY. YOU WERE OFF BY " + STR$(E) + " PERCENT."
90 PRINT "CORRECT ANSWER IS " + STR$(V) + " HOURS."
95 PRINT
100 PRINT "ANOTHER PROBLEM (YES OR NO)";
105 INPUT A$
110 IF A$ = "YES" THEN GOTO 15
999 EN
